// <auto-generated />
using System;
using LeadershipHelper.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeadershipHelper.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260429201531_RemoveSmsSupport")]
    partial class RemoveSmsSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeadershipHelper.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LeadershipHelper.Domain.Entities.AuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ExpiresUtc");

                    b.ToTable("AuthSessions");
                });

            modelBuilder.Entity("LeadershipHelper.Domain.Entities.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DetailsMarkdown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("DidHelp")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ExperienceDateUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SituationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SituationId");

                    b.HasIndex("UserId", "ExperienceDateUtc");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("LeadershipHelper.Domain.Entities.ExperienceActionState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastChangedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ResponseText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SituationActionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SituationActionId");

                    b.HasIndex("ExperienceId", "SituationActionId")
                        .IsUnique();

                    b.ToTable("ExperienceActionStates");
                });

            modelBuilder.Entity("LeadershipHelper.Domain.Entities.OtpChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("ConsumedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Contact", "CreatedUtc");

                    b.ToTable("OtpChallenges");
                });

            modelBuilder.Entity("LeadershipHelper.Domain.Entities.SavedSituation", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SituationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("SavedUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("UserId", "SituationId");

                    b.ToTable("SavedSituations");
                });

            modelBuilder.Entity("LeadershipHelper.Domain.Entities.Situation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsCommunity")
                        .HasColumnType("bit");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorName");

                    b.HasIndex("Title");

                    b.ToTable("Situations");
                });

            modelBuilder.Entity("LeadershipHelper.Domain.Entities.SituationAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PromptMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresTextResponse")
                        .HasColumnType("bit");

                    b.Property<Guid>("SituationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SituationId");

                    b.ToTable("SituationActions");
                });

            modelBuilder.Entity("LeadershipHelper.Domain.Entities.Experience", b =>
                {
                    b.HasOne("LeadershipHelper.Domain.Entities.Situation", "Situation")
                        .WithMany()
                        .HasForeignKey("SituationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Situation");
                });

            modelBuilder.Entity("LeadershipHelper.Domain.Entities.ExperienceActionState", b =>
                {
                    b.HasOne("LeadershipHelper.Domain.Entities.Experience", "Experience")
                        .WithMany("ActionStates")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeadershipHelper.Domain.Entities.SituationAction", "SituationAction")
                        .WithMany()
                        .HasForeignKey("SituationActionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Experience");

                    b.Navigation("SituationAction");
                });

            modelBuilder.Entity("LeadershipHelper.Domain.Entities.SituationAction", b =>
                {
                    b.HasOne("LeadershipHelper.Domain.Entities.Situation", "Situation")
                        .WithMany("Actions")
                        .HasForeignKey("SituationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Situation");
                });

            modelBuilder.Entity("LeadershipHelper.Domain.Entities.Experience", b =>
                {
                    b.Navigation("ActionStates");
                });

            modelBuilder.Entity("LeadershipHelper.Domain.Entities.Situation", b =>
                {
                    b.Navigation("Actions");
                });
#pragma warning restore 612, 618
        }
    }
}
